// Dilution Protocol Data - Complete dataset from MOH Dilution Guideline for Injectable Drugs (Dec 2020)
// All 36 injectable antimicrobial drugs from the official MOH guideline

export const DILUTION_DATA = [
    {
        id: "dilution-001",
        genericName: "Acyclovir",
        brandName: "Vaxcel® Acyclovir IV For Infusion",
        strength: "250mg",
        reconstitution: "Reconstitute 1 vial (250mg) with 10ml WFI or NS to provide a solution containing 25mg/ml",
        furtherDilution: "Dilute the required volume of reconstituted solution to give a concentration not greater than 5mg/ml (0.5% w/v). For children and neonates, dilute 4ml reconstituted solution (100mg) added to 20ml of infusion fluid. For adults, use 100ml infusion bags.",
        diluents: ["NS"],
        administration: "IV infusion: Administer by slow IV infusion over 1 hour",
        storage: "After reconstitution: 48 hours | After dilution: 48 hours | Protect from light | DO NOT REFRIGERATE",
        remarks: "Do not give by IV bolus, IM or subcutaneous route. Beware that too-rapid infusion may damage renal tubules.",
        category: "Antiviral"
    },
    {
        id: "dilution-002",
        genericName: "Amikacin",
        brandName: "Apalin",
        strength: "500mg/2ml",
        reconstitution: "Not required",
        furtherDilution: "Add 500mg amikacin solution to 100-200ml diluent",
        diluents: ["NS", "D5"],
        administration: "IM or IV infusion. Adult: infuse slowly over 30-60 minutes | Infants: infuse slowly over 1-2 hours",
        storage: "After dilution: RT (25°C) 24 hours | Fridge (4°C) 60 days",
        remarks: "Slow IV infusion may help to avoid neuromuscular blockade. Do not physically premix with other drugs.",
        category: "Aminoglycoside"
    },
    {
        id: "dilution-003",
        genericName: "Amoxicillin & Clavulanate",
        brandName: "Clavam For Injection BP",
        strength: "1.2g",
        reconstitution: "Reconstitute 1 vial (1.2g) with 20ml WFI (Final volume 20.9ml)",
        furtherDilution: "IV infusion: Dilute the reconstituted solution to 100ml diluent",
        diluents: ["NS", "WFI"],
        administration: "Slow IV bolus: Administer slowly over 3-4 minutes within 20 minutes of reconstitution | IV infusion: Administer over 30-40 minutes",
        storage: "After reconstitution: 20 minutes | After dilution: RT 4 hours | Fridge 8 hours",
        remarks: "Color may range from cream to pale yellow. Not suitable for IM administration. Less stable in glucose/dextrose infusions. Should not be mixed with blood products or protein fluids.",
        category: "Penicillin + Beta-lactamase Inhibitor"
    },
    {
        id: "dilution-004",
        genericName: "Amphotericin B",
        brandName: "Photericin B For Injection USP",
        strength: "50mg",
        reconstitution: "Reconstitute 1 vial (50mg) with 10ml WFI. Shake immediately until clear colloidal solution.",
        furtherDilution: "Further dilute to 0.1mg/ml concentration (0.25mg/ml for central line). Final concentration should not exceed these limits.",
        diluents: ["D5"],
        administration: "IV infusion: Administer by slow IV infusion over 2-6 hours depending on dose. Single IV test dose (1mg in 20ml D5) over 20-30 minutes may be preferred.",
        storage: "After reconstitution: RT 24 hours | Fridge 7 days | After dilution: RT 24 hours | Fridge 2 days | Protected from light",
        remarks: "Monitor temperature, pulse, respiration, BP every 30 minutes for 2-4 hours. Rapid IV infusion (< 1 hour) associated with hyperkalemia and arrhythmias. Do not reconstitute with saline. In-line filter (≥1 micron) may be used.",
        category: "Antifungal"
    },
    {
        id: "dilution-005",
        genericName: "Ampicillin",
        brandName: "Kampibiotic Injection",
        strength: "500mg",
        reconstitution: "IV: Dissolve 1 vial (500mg) in 10ml WFI | IM: Dilute 1 vial (500mg) with 1.5ml WFI",
        furtherDilution: "IV infusion: Dilute with 50-100ml NS (maximum concentration: 30mg/ml)",
        diluents: ["NS"],
        administration: "Slow IV bolus: Administer slowly over 3-4 minutes. Do not exceed 100mg/minute | Intermittent IV infusion: Administer over 15-30 minutes | IM",
        storage: "Use immediately",
        remarks: "Too-rapid infusion may cause seizures. Do not mix beta-lactam antibiotics with aminoglycosides. If prescribed concurrently, administer at separate sites at least 1 hour apart.",
        category: "Penicillin"
    },
    {
        id: "dilution-006",
        genericName: "Ampicillin & Sulbactam",
        brandName: "Amsubac Injection",
        strength: "1.5g (Ampicillin 1g + Sulbactam 500mg)",
        reconstitution: "IV: Reconstitute 1 vial (1.5g) with 3.2ml WFI. Allow foaming to dissipate | IM: Reconstitute with 3.2ml WFI or 0.5% lignocaine HCl",
        furtherDilution: "IV infusion: Further dilute to 50-100ml diluent",
        diluents: ["NS"],
        administration: "Slow IV bolus: Administer slowly over minimum 3 minutes | IV infusion: Administer over 15-30 minutes | IM: Deep IM injection",
        storage: "Not specified",
        remarks: "Do not mix or give through same IV line with aminoglycosides. Rapid infusion may cause seizures.",
        category: "Penicillin + Beta-lactamase Inhibitor"
    },
    {
        id: "dilution-007",
        genericName: "Anidulafungin",
        brandName: "Eraxis",
        strength: "100mg",
        reconstitution: "Reconstitute 1 vial (100mg) with 30ml WFI to provide 3.33mg/ml. Reconstitution time can be up to 5 minutes.",
        furtherDilution: "100mg dose: Add 30ml reconstituted to 100ml diluent (130ml total, 0.77mg/ml final) | 200mg dose: Add 60ml reconstituted to 200ml diluent (260ml total, 0.77mg/ml final)",
        diluents: ["NS", "D5"],
        administration: "IV infusion ONLY. Rate should not exceed 1.1mg/minute (1.4ml/min or 84ml/hour). Duration: 100mg over 90 minutes | 200mg over 180 minutes",
        storage: "After reconstitution: RT 24 hours | After dilution: RT 48 hours | Frozen 72 hours | For single use only",
        remarks: "Anaphylactic reactions and infusion-related adverse events reported. Infusion-related events infrequent when rate does not exceed 1.1mg/minute. Do not give as IV bolus.",
        category: "Antifungal"
    },
    {
        id: "dilution-008",
        genericName: "Artesunate",
        brandName: "Artesun Powder For Injection",
        strength: "60mg",
        reconstitution: "Reconstitute 1 vial (60mg) with provided diluent (5% sodium bicarbonate). Shake for 2-3 minutes until clear solution.",
        furtherDilution: "IV: Dilute 1ml reconstituted with 5ml diluent = 6ml total (10mg/ml) | IM: Dilute 1ml reconstituted with 2ml diluent = 3ml total (20mg/ml)",
        diluents: ["NS", "D5"],
        administration: "Slow IV bolus: Administer required dose slowly at 3-4ml/minute | IM",
        storage: "Use immediately",
        remarks: "Do not use in intravenous drip. Discard if solution not clear.",
        category: "Antimalarial"
    },
    {
        id: "dilution-009",
        genericName: "Azithromycin",
        brandName: "Vaxcel® Azithromycin IV For Infusion",
        strength: "500mg",
        reconstitution: "Reconstitute 1 vial (500mg) with 4.8ml WFI to obtain 100mg/ml",
        furtherDilution: "Add 5ml reconstituted to 500ml diluent (1mg/ml, infuse over 3 hours) OR add 5ml reconstituted to 250ml diluent (2mg/ml, infuse over 1 hour)",
        diluents: ["NS", "D5"],
        administration: "IV infusion: 500mg dose over minimum 1 hour. Do not administer as IV bolus or IM injection.",
        storage: "After reconstitution: RT (25±2°C) 24 hours | After dilution: RT (<25°C) 24 hours | Fridge (2-8°C) 7 days",
        remarks: "Do not add other substances or medications to azithromycin or infuse simultaneously through same IV line.",
        category: "Macrolide"
    },
    {
        id: "dilution-010",
        genericName: "Benzathine Penicillin",
        brandName: "Benzapen Sterile Penicillin G Benzathine USP",
        strength: "2.4 Mega Units",
        reconstitution: "Reconstitute with 8ml WFI",
        furtherDilution: "Not required",
        diluents: [],
        administration: "IM only. Avoid sciatic nerve damage in infants/small children - do not inject upper outer quadrant of buttock except in special cases.",
        storage: "Use immediately",
        remarks: "Alert patient to potential allergic reactions. Observe patient for 30 minutes after administration. Must NOT be injected subcutaneously, intravenously, intrathecally or into body cavities.",
        category: "Penicillin"
    },
    {
        id: "dilution-011",
        genericName: "Benzylpenicillin",
        brandName: "Bepen Injection",
        strength: "1MU (600mg), 5MU (3g)",
        reconstitution: "1MU vial with 2ml or more WFI | 5MU vial with 10ml or more WFI",
        furtherDilution: "Intermittent IV infusion: Dilute in 50-100ml NS | Continuous IV infusion: Dilute in 1000-2000ml NS",
        diluents: ["NS"],
        administration: "IM: Alternate sites for repeated injections | Intermittent IV infusion: Over 1-2 hours (adults) | 15-30 minutes (children/infants) | Continuous IV infusion: Over 24 hours (preferred for large doses)",
        storage: "After reconstitution: RT 2 days | Fridge 6 days | Reconstituted solutions intended for immediate administration",
        remarks: "Should be administered separately from solutions containing metal ions. Too-rapid infusion may cause electrolyte imbalance or seizures.",
        category: "Penicillin"
    },
    {
        id: "dilution-012",
        genericName: "Caspofungin Acetate",
        brandName: "Cancidas® For Injection",
        strength: "50mg, 70mg",
        reconstitution: "Bring refrigerated vial to RT. 50mg vial: Add 10.5ml NS or WFI (5.2mg/ml) | 70mg vial: Add 10.5ml NS or WFI (7.2mg/ml)",
        furtherDilution: "70mg dose: Transfer 5ml to each of two 100ml IV bags (0.33mg/ml each) | 50mg dose: Transfer 10ml to 100ml IV bag (0.45mg/ml) | Pediatric: Dilute to 250ml or reduced volume, max 0.5mg/ml",
        diluents: ["NS", "0.45% Sodium Chloride (Pediatric)"],
        administration: "IV infusion ONLY. Administer slowly over approximately 1 hour. For 70mg dose, administer each bag sequentially over 30 minutes.",
        storage: "After reconstitution: RT (<25°C) 24 hours | After dilution: RT 24 hours | Fridge 48 hours | Lyophilized powder: Store at 2-8°C",
        remarks: "Do not use diluents containing dextrose. Do not mix or co-infuse with other medications. Visually inspect for particulate matter or discoloration.",
        category: "Antifungal"
    },
    {
        id: "dilution-013",
        genericName: "Cefazolin",
        brandName: "Cefazolin Sandoz®",
        strength: "1g",
        reconstitution: "IV: Reconstitute 1 vial (1g) with 4ml NS or WFI | IM: Reconstitute with 4ml 0.5% lidocaine solution",
        furtherDilution: "IV infusion: Dilute in 50-100ml NS",
        diluents: ["NS"],
        administration: "Slow IV bolus: Administer slowly over 3-5 minutes (up to 1g) | IV infusion: doses >1g over 20-30 minutes | IM: Inject into major muscle mass",
        storage: "Use immediately",
        remarks: "Do not mix in same infusion with aminoglycoside as both drugs may be inactivated.",
        category: "Cephalosporin (1st Gen)"
    },
    {
        id: "dilution-014",
        genericName: "Cefepime",
        brandName: "Cefmex Powder For Injection",
        strength: "1g",
        reconstitution: "IV: Reconstitute 1 vial (1g) with 10ml diluent (approx 90mg/ml) | IM: Reconstitute with 3ml diluent (approx 230mg/ml)",
        diluents: ["WFI", "D5", "NS"],
        furtherDilution: "IV infusion: Dilute to 50-100ml diluent",
        administration: "Slow IV bolus: Administer slowly over 3-5 minutes | IV infusion: Administer over 30 minutes | IM: Deep IM injection into large muscle mass",
        storage: "After reconstitution & dilution: Fridge (2-8°C) 48 hours | Compatible at 1-40mg/ml",
        remarks: "Inspect visually for particulate matter before administration. Do not use if particulate matter present.",
        category: "Cephalosporin (4th Gen)"
    },
    {
        id: "dilution-015",
        genericName: "Cefoperazone",
        brandName: "Bicafar",
        strength: "1g",
        reconstitution: "IV: Reconstitute 1g with 5ml D5, NSD5, NS or WFI. For continuous IV, dissolve each gram in 5ml WFI | IM: Use 2-step process with WFI then lidocaine for concentrations ≥250mg/ml",
        furtherDilution: "IV (max 2g/day): Dilute to 100mg/ml | Intermittent IV infusion: Dilute with 20-100ml diluent",
        diluents: ["D5", "NSD5", "NS"],
        administration: "Slow IV bolus: Over 3-5 minutes | Intermittent IV infusion: Over 15 minutes to 1 hour | IM: Deep IM into gluteus maximus or anterior thigh",
        storage: "After reconstitution (300mg/ml): RT (15-25°C) 24 hours | Fridge (2-8°C) 5 days",
        remarks: "Cefoperazone and aminoglycoside solutions should not be directly mixed - physical incompatibility.",
        category: "Cephalosporin (3rd Gen)"
    },
    {
        id: "dilution-016",
        genericName: "Cefoperazone & Sulbactam",
        brandName: "Vaxcel® Cefobactam Injection",
        strength: "1g (Cefoperazone 500mg + Sulbactam 500mg)",
        reconstitution: "IV: Reconstitute 1 vial (1g) with 3.4ml WFI, D5 or NS | IM: Reconstitute with 3.4ml WFI then dilute with 2% lidocaine to 125mg/125mg per ml in 0.5% lidocaine",
        furtherDilution: "Intermittent IV infusion: Dilute reconstituted solution to 20ml with same solution",
        diluents: ["WFI", "NS", "D5"],
        administration: "Slow IV bolus: Over minimum 3 minutes | Intermittent IV infusion: Over 15-60 minutes | IM",
        storage: "After reconstitution: RT (<25°C) 24 hours",
        remarks: "Sulbactam/cefoperazone and aminoglycosides should not be directly mixed - physical incompatibility.",
        category: "Cephalosporin + Beta-lactamase Inhibitor"
    },
    {
        id: "dilution-017",
        genericName: "Cefotaxime",
        brandName: "Rekaxime Injection",
        strength: "500mg, 1g",
        reconstitution: "500mg vial with 2ml WFI | 1000mg vial with 4ml WFI",
        furtherDilution: "Short infusion: Dilute in 40ml WFI or 10% glucose | Continuous drip: Dilute in 100ml isotonic saline or glucose",
        diluents: ["NS", "D5", "D10"],
        administration: "Slow IV bolus: Over 3-5 minutes | Short infusion: Infuse in approximately 20 minutes | Continuous drip: Infuse over 50-60 minutes | IM: Deep into gluteus, max 4ml per side. If daily dose >2g, IV preferred",
        storage: "Cefotaxime solutions: RT (<25°C) 24 hours | Should be administered as soon as prepared",
        remarks: "Incompatible with alkaline solutions (sodium bicarbonate) and hetastarch. Do not mix with aminoglycosides or metronidazole. Pale yellow color does not mean impaired efficacy. IV bolus <1 minute can cause life-threatening arrhythmias.",
        category: "Cephalosporin (3rd Gen)"
    },
    {
        id: "dilution-018",
        genericName: "Ceftazidime",
        brandName: "Cefatum Injection",
        strength: "1g, 2g",
        reconstitution: "1g IM: 3ml 0.5% lignocaine (260mg/ml) | 1g IV: 10ml WFI (90mg/ml) | 2g IV: 10ml WFI (170mg/ml)",
        diluents: ["WFI", "0.5% lignocaine"],
        furtherDilution: "Intermittent IV infusion: Dilute in 100ml diluent",
        administration: "Slow IV bolus: Over 3-5 minutes | Intermittent IV infusion: Over 30 minutes | IM: Deep IM into large muscle mass",
        storage: "After reconstitution with WFI: RT 12 hours | Fridge 7 days | With lignocaine: RT 6 hours | Fridge 4 days | After dilution (1-40mg/ml): RT 12 hours | Fridge 7 days",
        remarks: "Sodium bicarbonate not recommended as diluent. Color ranges from light yellow to amber depending on concentration/storage. Individual doses >1g should be given IV. Do not mix beta-lactams with aminoglycosides.",
        category: "Cephalosporin (3rd Gen)"
    },
    {
        id: "dilution-019",
        genericName: "Ceftriaxone",
        brandName: "Unocef Injection",
        strength: "500mg, 1g",
        reconstitution: "IM: 500mg vial with 1.8ml WFI (250mg/ml) or 1ml WFI (350mg/ml) | 1g vial with 3.6ml WFI (250mg/ml) or 2.1ml WFI (350mg/ml) | IV: 500mg with 4.8ml WFI | 1g with 9.6ml WFI",
        furtherDilution: "IV infusion: Dilute reconstituted solution to 50 or 100ml diluent",
        diluents: ["WFI", "NS", "D5", "1% Lidocaine (IM only)"],
        administration: "IV infusion: Administer over 30 minutes (concentration 10-40mg/ml recommended) | IM: Deep IM into large muscle mass. Doses >1g distributed between two sites",
        storage: "Varies with diluent. WFI/NS/D5 at 100mg/ml: RT 3 days | Fridge 10 days | At 250-350mg/ml: RT 24 hours | Fridge 3 days",
        remarks: "DO NOT use diluents containing calcium (Ringer's or Hartmann's solution). Must not be administered with calcium-containing IV solutions. After reconstitution, protection from normal light is not necessary.",
        category: "Cephalosporin (3rd Gen)"
    },
    {
        id: "dilution-020",
        genericName: "Cefuroxime",
        brandName: "Pharmaniaga Cefuroxime Injection",
        strength: "750mg, 1.5g",
        reconstitution: "IM: 750mg vial with 3ml WFI | IV: 750mg vial with 6ml WFI or 1.5g vial with 12ml WFI",
        furtherDilution: "IV infusion: Further dilute to 50-100ml diluent",
        diluents: ["NS", "D5"],
        administration: "Slow IV injection: Over 3-5 minutes | IV infusion: Over 30 minutes | IM: Deep IM injection",
        storage: "Varies with diluent and concentration (RT 5-24 hours, Fridge 24-48 hours depending on formulation)",
        remarks: "Do not add to solutions of aminoglycosides or sodium bicarbonate.",
        category: "Cephalosporin (2nd Gen)"
    },
    {
        id: "dilution-021",
        genericName: "Clindamycin",
        brandName: "Generic",
        strength: "300mg/2ml, 600mg/4ml",
        reconstitution: "Not required",
        furtherDilution: "300mg to 50ml | 600mg to 50ml | 900mg to 50-100ml | 1200mg to 100ml",
        diluents: ["NS", "D5"],
        administration: "300mg over 10 minutes | 600mg over 20 minutes | 900mg over 30 minutes | 1200mg over 40 minutes | Max rate: 30mg/minute",
        storage: "After dilution: RT 16-24 hours (varies by diluent) | Fridge up to 32 days",
        remarks: "Do not inject undiluted as bolus. Do not use if precipitate forms. Reduce rate if adverse reactions occur.",
        category: "Lincosamide"
    },
    {
        id: "dilution-022",
        genericName: "Cloxacillin",
        brandName: "Generic",
        strength: "500mg, 1g",
        reconstitution: "IV: 500mg with 5ml WFI (100mg/ml) | 1g with 10ml WFI (100mg/ml) | IM: 500mg with 2ml WFI (250mg/ml)",
        furtherDilution: "IV infusion: Dilute to 50-100ml diluent",
        diluents: ["NS", "D5", "WFI"],
        administration: "Slow IV injection: Over 3-4 minutes | IV infusion: Over 30-60 minutes | IM: Deep IM",
        storage: "After reconstitution: Use within 1-2 hours | After dilution: Use promptly",
        remarks: "Incompatible with aminoglycosides - administer separately. Do not mix in same syringe/infusion.",
        category: "Penicillin"
    },
    {
        id: "dilution-023",
        genericName: "Ertapenem",
        brandName: "Invanz® Injection",
        strength: "1g",
        reconstitution: "IV infusion: Reconstitute with 10ml sterile WFI, NS or bacteriostatic WFI | IM: Reconstitute with 3.2ml 1% lidocaine HCl injection (without epinephrine)",
        furtherDilution: "IV infusion: Transfer reconstituted to 50ml NS",
        diluents: ["NS"],
        administration: "IV infusion: Administer over 30 minutes | IM: Deep IM injection into large muscle mass (gluteal or lateral thigh)",
        storage: "After reconstitution: Use immediately (within 6 hours) | After dilution for infusion: RT 6 hours | Fridge 24 hours",
        remarks: "Must NOT be mixed or co-infused with other medications. Do not use diluents containing dextrose.",
        category: "Carbapenem"
    },
    {
        id: "dilution-024",
        genericName: "Erythromycin Lactobionate",
        brandName: "Eritrotex Injection",
        strength: "500mg",
        reconstitution: "Reconstitute 1 vial (500mg) with 10ml WFI to obtain 50mg/ml",
        furtherDilution: "IV infusion: Dilute with not less than 100ml diluent to final concentration 1-5mg/ml",
        diluents: ["NS", "D5"],
        administration: "Intermittent IV infusion: Administer over 60 minutes every 6 hours | Continuous IV infusion: Administer over 24 hours",
        storage: "Should be freshly prepared and unused portion discarded",
        remarks: "Erythromycin IV may cause phlebitis. Dilute appropriately and infuse slowly to minimize risk.",
        category: "Macrolide"
    },
    {
        id: "dilution-025",
        genericName: "Ganciclovir",
        brandName: "Cymevene®",
        strength: "500mg",
        reconstitution: "Reconstitute with 10ml WFI (50mg/ml). Do not use bacteriostatic water.",
        furtherDilution: "Dilute in 100ml diluent (concentration should not exceed 10mg/ml)",
        diluents: ["NS", "D5"],
        administration: "IV infusion: Administer over 1 hour. Do not give by rapid or bolus IV injection.",
        storage: "After reconstitution: Use within 12 hours | Do not refrigerate | After dilution: Use within 24 hours if refrigerated",
        remarks: "Do not administer IM or SC. Hydration recommended before infusion. Handle as cytotoxic agent.",
        category: "Antiviral"
    },
    {
        id: "dilution-026",
        genericName: "Gentamicin",
        brandName: "Garasent",
        strength: "80mg/2ml",
        reconstitution: "Not required",
        furtherDilution: "IV infusion: Dilute in 50-200ml diluent",
        diluents: ["NS", "D5"],
        administration: "IM or IV infusion over 30-60 minutes",
        storage: "Not specified",
        remarks: "Should not be physically premixed with other drugs.",
        category: "Aminoglycoside"
    },
    {
        id: "dilution-027",
        genericName: "Imipenem & Cilastatin",
        brandName: "Imipenem/Cilastatin Kabi Powder For Solution",
        strength: "500mg",
        reconstitution: "Reconstitute with 100ml compatible diluent",
        furtherDilution: "May be added to compatible IV solutions",
        diluents: ["NS", "D5"],
        administration: "IV infusion: 500mg over 20-30 minutes | 1g over 40-60 minutes",
        storage: "After reconstitution: RT 4 hours | After dilution: Varies by diluent (4-24 hours)",
        remarks: "Should not be mixed with or physically added to other antibiotics. May be administered through same tubing if flushed between medications.",
        category: "Carbapenem"
    },
    {
        id: "dilution-028",
        genericName: "Meropenem",
        brandName: "Nuronem Injection",
        strength: "500mg, 1g",
        reconstitution: "Reconstitute 1 vial (500mg) with 10ml WFI (5ml WFI per 250mg) to obtain 50mg/ml",
        furtherDilution: "IV infusion: Dilute reconstituted solution with 50-200ml diluent",
        diluents: ["NS", "D5"],
        administration: "Slow IV bolus: Administer slowly over 5 minutes | IV infusion: Administer over 15-30 minutes",
        storage: "After dilution in NS: RT 8 hours | Fridge 48 hours | After dilution in D5: RT 3 hours | Fridge 14 hours | Do not freeze",
        remarks: "Should not be mixed in solution with other antibiotics.",
        category: "Carbapenem"
    },
    {
        id: "dilution-029",
        genericName: "Micafungin",
        brandName: "Mycamine® Powder For Solution",
        strength: "50mg, 100mg",
        reconstitution: "Add 5ml NS or D5 to vial. Gently swirl (do not shake vigorously)",
        furtherDilution: "Add reconstituted solution to 100ml NS or D5 infusion bag",
        diluents: ["NS", "D5"],
        administration: "IV infusion ONLY. Flush existing IV line with NS prior to infusion. Administer over approximately 1 hour.",
        storage: "After reconstitution: RT 24 hours | After dilution: 6 hours without light protection | 24 hours with light protection",
        remarks: "Concentrate should be used immediately for dilution. Single use only - discard residue. Place in opaque bag for light protection.",
        category: "Antifungal"
    },
    {
        id: "dilution-030",
        genericName: "Netilmicin",
        brandName: "Lotifar Injection",
        strength: "150mg/2ml, 100mg/2ml",
        reconstitution: "Not required",
        furtherDilution: "IV infusion: Dilute single dose in 50-200ml diluent",
        diluents: ["NS", "D5"],
        administration: "Slow IV bolus: Administer over 3-5 minutes | IV infusion: Administer over 1.5-2 hours",
        storage: "After dilution: RT (<25°C) 7 days at 3mg/ml concentration",
        remarks: "Should not be physically premixed with other drugs. Administer separately.",
        category: "Aminoglycoside"
    },
    {
        id: "dilution-031",
        genericName: "Pentamidine Isethionate",
        brandName: "DBL™ Pentamidine Isethionate For Injection",
        strength: "300mg",
        reconstitution: "Reconstitute 1 vial (300mg) with 3-5ml WFI",
        furtherDilution: "Dilute required dose in 50-250ml diluent",
        diluents: ["NS", "D5"],
        administration: "IV infusion: Administer over at least 60 minutes",
        storage: "After reconstitution: RT (21±2°C) 48 hours | Fridge (2-8°C) 48 hours | After dilution: 24 hours (both RT and fridge) at 1-2.5mg/ml",
        remarks: "Direct bolus IV or rapid administration must NOT be used. Keep patient supine during administration to minimize hypotension.",
        category: "Antiprotozoal"
    },
    {
        id: "dilution-032",
        genericName: "Piperacillin & Tazobactam",
        brandName: "Tapicin Powder For Injection",
        strength: "4.5g (Piperacillin 4g + Tazobactam 0.5g)",
        reconstitution: "Reconstitute 1 vial (4.5g) with 20ml diluent",
        diluents: ["WFI", "NS", "D5"],
        furtherDilution: "IV infusion: Dilute reconstituted solution with 50-150ml diluent",
        administration: "Slow IV bolus: Administer over 3-5 minutes | IV infusion: Administer over 20-30 minutes",
        storage: "After reconstitution: RT (25°C) 24 hours | Fridge (2-8°C) 7 days",
        remarks: "Contains no preservative - use aseptic technique. When used with another antibiotic, administer separately. Do not use with sodium bicarbonate or add to blood products/albumin.",
        category: "Penicillin + Beta-lactamase Inhibitor"
    },
    {
        id: "dilution-033",
        genericName: "Sulphamethoxazole-Trimethoprim",
        brandName: "DBL™ Sulfamethoxazole & Trimethoprim Concentrate",
        strength: "5ml per ampoule (SMX 400mg + TMP 80mg)",
        reconstitution: "Not required",
        furtherDilution: "1 ampoule (5ml) to 125ml diluent | 2 ampoules (10ml) to 250ml | 3 ampoules (15ml) to 500ml",
        diluents: ["D5", "NS", "D10"],
        administration: "IV infusion: Administer slowly over 60-90 minutes. Duration should not exceed 1.5 hours.",
        storage: "After dilution: RT 24 hours | Do NOT refrigerate prepared solution",
        remarks: "Must be diluted prior to administration. Administer IV only as infusion - not undiluted or directly into tube. Shake well to ensure mixing. Discard if turbidity or crystallization appears.",
        category: "Sulfonamide + Folate Antagonist"
    },
    {
        id: "dilution-034",
        genericName: "Vancomycin",
        brandName: "Celovan Powder For Solution",
        strength: "500mg",
        reconstitution: "Dissolve 500mg in 10ml WFI to obtain 50mg/ml",
        furtherDilution: "Intermittent IV infusion: Dilute with at least 100ml diluent (max 5mg/ml, or up to 10mg/ml for fluid-restricted patients)",
        diluents: ["NS", "D5"],
        administration: "Intermittent IV infusion: Administer over at least 60 minutes (max rate 10mg/minute). 1g dose usually given over 2 hours.",
        storage: "After dilution: RT (<25°C) 48 hours | Fridge (2-8°C) 48 hours",
        remarks: "Not for IM administration. Watch for 'red-man syndrome' - nonallergic histamine reaction from rapid IV. Symptoms: hypotension, pruritus, maculopapular rash on face/neck/trunk/limbs.",
        category: "Glycopeptide"
    },
    {
        id: "dilution-035",
        genericName: "Voriconazole",
        brandName: "Vfend®",
        strength: "200mg",
        reconstitution: "Reconstitute 1 vial (200mg) with 19ml WFI (10mg/ml, extractable volume 20ml)",
        furtherDilution: "Further dilute required volume to final concentration 0.5-5mg/ml according to patient body weight",
        diluents: ["NS", "HSD5", "D5"],
        administration: "IV infusion ONLY. Administer over 1-2 hours. Maximum rate: 3mg/kg/hour",
        storage: "After reconstitution: Fridge (2-8°C) 24 hours | Product must be used immediately",
        remarks: "Must NOT be infused with blood products or concentrated electrolytes. Not for IV bolus. Must NOT be diluted with 4.2% sodium bicarbonate.",
        category: "Antifungal"
    },
    {
        id: "dilution-036",
        genericName: "Zidovudine",
        brandName: "Retrovir™",
        strength: "200mg/20ml",
        reconstitution: "Not required",
        furtherDilution: "Mix required dose with diluent to obtain 2mg/ml or 4mg/ml concentration. Use full aseptic technique.",
        diluents: ["D5"],
        administration: "IV infusion: Administer slowly over 1 hour. Avoid rapid infusion or bolus injection.",
        storage: "After dilution: RT (25°C) 48 hours | Fridge (5°C) 48 hours | Discard unused portion",
        remarks: "Do not administer as IM injection. Must be DILUTED prior to administration. Discard if visible turbidity appears before/after dilution or during infusion.",
        category: "Antiviral"
    }
];

export const DILUTION_METADATA = {
    title: "Dilution Guideline for Injectable Drugs",
    version: "Part I - Antimicrobial",
    publicationDate: "December 2020",
    reviewDate: "December 2025",
    author: "Medication Safety Section, Pharmacy Practice and Development Division, Pharmaceutical Services Programme, Ministry of Health Malaysia",
    totalDrugs: 36,
    disclaimer: "This guideline serves as a general reference for healthcare professionals. Information extracted from package inserts for brands used in MOH at time of publication. Users strongly advised to refer to product package insert currently used at respective facilities."
};
